name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Git config
      run: |
        git config --local user.email "ewan_forbes@yahoo.co.uk"
        git config --local user.name "redemptive"
        git remote set-url origin https://${{secrets.GH_TOKEN}}@github.com/redemptive/redemptive.github.io.git
    - name: npm install
      run: npm install
    - name: eslint
      run: npm run lint
    - name: Run tests
      run: npm run ci-test
    - name: Build package
      run: npm build
    - name: Deploy to GH pages
      run: npm run deploy